import { supabase } from "../supabase/supabaseClient.js";

let empleadosHoy = [], areasHoy = [], resumenHoy = null, cumplimiento = [], reincidencia = [], diasIngreso = [];

const $ = (id) => document.getElementById(id);
const setText = (id,v) => { const e=$(id); if(e) e.textContent=v ?? ""; };
const esc = (v) => String(v ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
const norm = (v) => String(v??"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function hora(v){if(!v)return "—";const m=String(v).match(/(\d{2}:\d{2})(?::\d{2})?/);return m?m[1]:String(v).slice(0,5)}
function fechaTxt(v){if(!v)return "—";try{return new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString("es-CO",{day:"2-digit",month:"short",year:"numeric"})}catch{return v}}
function num(v,d=2){return Number(v||0).toLocaleString("es-CO",{minimumFractionDigits:d,maximumFractionDigits:d})}
function sesion(){try{return JSON.parse(localStorage.getItem("ccp_sesion")||"null")}catch{return null}}
function pintarUsuario(){const s=sesion();if(!s){location.href="login.html";return false}setText("nombreUsuario",s.nombre_completo||`${s.nombres||""} ${s.apellidos||""}`.trim()||s.usuario||"Usuario");setText("rolUsuario",s.rol||"Sin rol");setText("fechaDashboard",new Date().toLocaleDateString("es-CO",{weekday:"long",year:"numeric",month:"long",day:"numeric"}));return true}
function rango(){return {desde:$("filtroFechaDesde")?.value||iso(new Date()),hasta:$("filtroFechaHasta")?.value||iso(new Date())}}
function initRango(){const h=new Date(),d=new Date();d.setDate(h.getDate()-6);$("filtroFechaDesde").value=iso(d);$("filtroFechaHasta").value=iso(h)}

async function cargar(){
  setText("ultimaActualizacion","Actualizando..."); const r=rango(); const hoy=iso(new Date());
  const [res, areas, salidas, comp, reinc, dias] = await Promise.all([
    supabase.from("vw_centro_control_asistencia_hoy").select("*").maybeSingle(),
    supabase.from("vw_centro_control_areas_hoy").select("*").order("area_operativa"),
    supabase.from("vw_centro_control_salidas_hoy").select("*").order("primera_marcacion"),
    supabase.from("vw_centro_control_cumplimiento_semanal").select("*").lte("semana_inicio",r.hasta).gte("semana_fin",r.desde).order("horas_reales_consolidadas",{ascending:false}),
    supabase.from("vw_ayb_reincidencia_tardanzas").select("*").gte("ultima_fecha",r.desde).lte("ultima_fecha",r.hasta),
    supabase.from("vw_centro_control_dias_mayor_ingreso").select("*").gte("fecha",r.desde).lte("fecha",r.hasta).order("empleados_con_marcacion",{ascending:false}).limit(20)
  ]);
  for(const x of [res,areas,salidas,comp,reinc,dias]) if(x.error) console.warn(x.error);
  resumenHoy=res.data||null; areasHoy=areas.data||[]; empleadosHoy=salidas.data||[]; cumplimiento=comp.data||[]; reincidencia=reinc.data||[]; diasIngreso=dias.data||[];
  poblarAreas(); render(); setText("ultimaActualizacion",`Actualizado ${new Date().toLocaleTimeString("es-CO",{hour:"2-digit",minute:"2-digit"})}`);
}

function poblarAreas(){const s=$("filtroAreaGeneral"); if(!s)return; const actual=s.value; const arr=[...new Set(empleadosHoy.flatMap(x=>[x.grupo_nombre,x.proceso_nombre,x.area_ultima_marcacion,x.area_primera_marcacion]).filter(Boolean))].sort();s.innerHTML='<option value="">Todos</option>'+arr.map(x=>`<option>${esc(x)}</option>`).join("");if(arr.includes(actual))s.value=actual}
function coincide(x){const a=$("filtroAreaGeneral")?.value||"",q=norm($("filtroEmpleadoGeneral")?.value||""); if(a&&!String(`${x.grupo_nombre||""} ${x.proceso_nombre||""} ${x.area_primera_marcacion||""} ${x.area_ultima_marcacion||""}`).includes(a))return false;if(q&&!norm(`${x.empleado||""} ${x.cedula||""} ${x.cargo||""}`).includes(q))return false;return true}
function renderKPIs(){setText("kpiEmpleados",resumenHoy?.empleados_con_registro||0);setText("kpiMarcaciones",resumenHoy?.total_marcaciones||0);setText("kpiEnCurso",resumenHoy?.jornadas_en_curso||0);setText("kpiSalidas",empleadosHoy.filter(x=>x.salida_registrada).length);setText("kpiAlertasAltas",resumenHoy?.alertas_altas||0);setText("kpiAreas",resumenHoy?.areas_activas||areasHoy.length)}
function renderAreas(){const t=$("tablaAreasReal");if(!areasHoy.length){t.innerHTML='<tr><td colspan="6" class="text-center text-muted">Sin actividad hoy.</td></tr>';return}t.innerHTML=areasHoy.map(x=>`<tr><td><strong>${esc(x.area_operativa)}</strong></td><td>${x.empleados}</td><td>${x.marcaciones}</td><td>${x.jornadas_en_curso}</td><td>${hora(x.primera_actividad)}</td><td>${hora(x.ultima_actividad)}</td></tr>`).join("")}
function renderEmpleados(){const f=empleadosHoy.filter(coincide),t=$("tablaEmpleadosReal");setText("contadorEmpleadosFiltrados",`${f.length} resultados`);if(!f.length){t.innerHTML='<tr><td colspan="6" class="text-center text-muted">Sin resultados.</td></tr>';return}t.innerHTML=f.map(x=>{const est=x.salida_registrada?'<span class="cc-badge cc-ok">Salida registrada</span>':'<span class="cc-badge cc-warn">En curso</span>';const ar=x.proceso_nombre||x.grupo_nombre||x.area_ultima_marcacion||x.area_primera_marcacion||"Sin clasificar";return `<tr><td><strong>${esc(x.empleado)}</strong><div class="cc-muted">${esc(x.cedula)}${x.cargo?` · ${esc(x.cargo)}`:""}</div></td><td>${esc(ar)}</td><td>${hora(x.primera_marcacion)}</td><td>${x.salida_registrada?hora(x.ultima_marcacion):"—"}</td><td>${x.total_marcaciones}</td><td>${est}</td></tr>`}).join("")}
function estadoCumpl(x){if(x.estado_cumplimiento==="datos_incompletos")return '<span class="cc-badge cc-warn">Datos incompletos</span>';if(x.estado_42==="excedio")return '<span class="cc-badge cc-info">Excedió 42</span>';if(x.estado_cumplimiento==="cumplio")return '<span class="cc-badge cc-ok">Cumplió</span>';return '<span class="cc-badge cc-bad">No cumplió</span>'}
function renderCumplimiento(){let f=cumplimiento.filter(coincide);const t=$("tablaCumplimientoSemanal");const ok=f.filter(x=>x.estado_cumplimiento==="cumplio").length;setText("kpiCumplimientoResumen",`${ok} cumplen · ${f.length} evaluados`);if(!f.length){t.innerHTML='<tr><td colspan="9" class="text-center text-muted">Aún no hay semanas comparables en el rango.</td></tr>';return}t.innerHTML=f.map(x=>`<tr><td><strong>${esc(x.empleado)}</strong><div class="cc-muted">${esc(x.cedula)}</div></td><td>${fechaTxt(x.semana_inicio)} – ${fechaTxt(x.semana_fin)}</td><td>${num(x.horas_programadas_netas)}</td><td><strong>${num(x.horas_reales_consolidadas)}</strong></td><td>${num(x.porcentaje_cumplimiento,1)}%</td><td>${estadoCumpl(x)}</td><td>${num(x.horas_faltantes_42)}</td><td>${x.total_alertas||0}</td><td><button class="btn btn-outline-secondary btn-sm" onclick="window.abrirAuditoriaSemanal('${esc(x.cedula)}','${esc(x.semana_inicio)}','${esc(x.semana_fin)}','${esc(x.empleado)}')">Auditar</button></td></tr>`).join("")}
function renderPuntualidad(){const f=reincidencia.filter(coincide);const tard=[...f].filter(x=>Number(x.tardanzas)>0).sort((a,b)=>Number(b.tardanzas)-Number(a.tardanzas)||Number(b.minutos_tarde_acumulados)-Number(a.minutos_tarde_acumulados)).slice(0,15);const sal=[...f].filter(x=>Number(x.salidas_anticipadas)>0).sort((a,b)=>Number(b.salidas_anticipadas)-Number(a.salidas_anticipadas)||Number(b.minutos_salida_anticipada_acumulados)-Number(a.minutos_salida_anticipada_acumulados)).slice(0,15);$("tablaTardanzas").innerHTML=tard.length?tard.map(x=>`<tr><td><strong>${esc(x.empleado)}</strong></td><td>${x.tardanzas}</td><td>${x.minutos_tarde_acumulados}</td><td>${fechaTxt(x.ultima_fecha)}</td></tr>`).join(""):'<tr><td colspan="4" class="text-center text-muted">Sin tardanzas calculables.</td></tr>';$("tablaSalidasAnticipadas").innerHTML=sal.length?sal.map(x=>`<tr><td><strong>${esc(x.empleado)}</strong></td><td>${x.salidas_anticipadas}</td><td>${x.minutos_salida_anticipada_acumulados}</td><td>${fechaTxt(x.ultima_fecha)}</td></tr>`).join(""):'<tr><td colspan="4" class="text-center text-muted">Sin salidas anticipadas calculables.</td></tr>'}
function renderDias(){const t=$("tablaDiasMayorIngreso");t.innerHTML=diasIngreso.length?diasIngreso.map(x=>`<tr><td>${fechaTxt(x.fecha)}</td><td><strong>${x.empleados_con_marcacion}</strong></td><td>${x.total_marcaciones}</td><td>${x.jornadas_en_curso}</td><td>${x.alertas}</td></tr>`).join(""):'<tr><td colspan="5" class="text-center text-muted">Aún no hay histórico suficiente.</td></tr>'}
function render(){renderKPIs();renderAreas();renderEmpleados();renderCumplimiento();renderPuntualidad();renderDias()}

window.abrirAuditoriaSemanal=async function(cedula,desde,hasta,nombre){const t=$("tablaAuditoriaSemanal");setText("auditoriaSubtitulo",`${nombre} · ${fechaTxt(desde)} – ${fechaTxt(hasta)}`);t.innerHTML='<tr><td colspan="9" class="text-center text-muted">Cargando...</td></tr>';const {data,error}=await supabase.from("vw_centro_control_auditoria_semanal").select("*").eq("cedula",cedula).gte("fecha",desde).lte("fecha",hasta).order("fecha");if(error)t.innerHTML=`<tr><td colspan="9" class="text-danger">${esc(error.message)}</td></tr>`;else t.innerHTML=(data||[]).map(x=>`<tr><td>${fechaTxt(x.fecha)}</td><td>${esc(x.turno||"—")}<div class="cc-muted">${esc(x.hora_inicio||"—")}–${esc(x.hora_fin||"—")}</div></td><td>${num(x.horas_programadas_netas)}</td><td>${x.horas_reales_pareadas==null?"—":num(x.horas_reales_pareadas)}</td><td>${hora(x.primera_marcacion)}</td><td>${hora(x.ultima_marcacion)}</td><td>${esc(x.estado_comparacion||"—")}</td><td>${x.total_alertas||0}</td><td>${x.conceptos_aprobados||0} · ${num(x.horas_conceptos_aprobadas||0)}</td></tr>`).join("")||'<tr><td colspan="9" class="text-center text-muted">Sin detalle.</td></tr>';bootstrap.Modal.getOrCreateInstance($("modalAuditoriaSemanal")).show()}

function eventos(){$("btnActualizarDashboard")?.addEventListener("click",()=>cargar().catch(e=>alert(e.message||e)));for(const id of ["filtroFechaDesde","filtroFechaHasta"])$(id)?.addEventListener("change",()=>cargar().catch(console.error));$("filtroAreaGeneral")?.addEventListener("change",render);$("filtroEmpleadoGeneral")?.addEventListener("input",render)}
document.addEventListener("DOMContentLoaded",async()=>{if(!pintarUsuario())return;initRango();eventos();try{await cargar()}catch(e){console.error(e);alert(`No fue posible cargar el Centro de Control: ${e.message||e}`)}});
