import { supabase } from '../supabase/supabaseClient.js';
import { asegurarSesion, rpcConSesion, esErrorAcceso, mostrarErrorAcceso, observarSesion, ErrorSesion } from './sesion-protegida.js?v=sesion-6-2-1';
import {METRIC_START,HISTORY_START,bogotaNow,iso,addDays,dates,dayMinute,clock,norm,buildModel,matchPerson,selectedEvents,selectedJourneys,summary,dailyFlow,areaFlow,heatmap,punctuality,mergeNotices} from './centro-control-metricas.js?v=cc-20260910-v2';

// Solo lectura. Los modulos de aprobacion y pago no se invocan desde aqui.
const $=id=>document.getElementById(id);
const txt=(id,value)=>{if($(id))$(id).textContent=value??'';};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=0)=>v===null||v===undefined?'\u2014':Number(v).toLocaleString('es-CO',{maximumFractionDigits:d});
const pretty=d=>d?`${d.slice(8,10)}/${d.slice(5,7)}/${d.slice(0,4)}`:'\u2014';
const monthStart=d=>d.slice(0,7)+'-01';
const monthEnd=d=>new Date(Date.UTC(+d.slice(0,4),+d.slice(5,7),0)).toISOString().slice(0,10);
const inRange=(d,r)=>d>=r.from&&d<=r.to;
const s={model:null,range:null,tab:'summary',page:0,loadToken:0,abort:null,channel:null,timer:null,debounce:null,lastLoaded:0,compliance:null,complianceKey:'',auditToken:0};
const stateLabels={puntual:['A tiempo','ok'],tarde:['Llegada tarde','bad'],justificada:['Descanso / novedad','info'],sin_programacion:['Sin programaci\u00f3n','warn'],sin_marca:['Sin marcaci\u00f3n; revisar','warn'],sin_entrada:['Sin entrada verificable','warn'],en_espera:['Jornada en curso','info'],futura:['Programaci\u00f3n futura',''],inferida:['Horario inferido; excluido',''],conflicto:['Programaciones en conflicto','warn'],sin_horario:['Sin horario comparable','']};
function pill(label,cl=''){return `<span class="cc-pill ${cl}">${esc(label)}</span>`;}
function empty(message='No hay registros para estos filtros.'){return `<p class="cc-empty">${esc(message)}</p>`;}
function table(headers,rows){return rows.length?`<div class="cc-table-scroll"><table class="cc-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty();}
function filters(extra={}){return {...(s.range||{from:$('ccFrom').value,to:$('ccTo').value}),population:$('ccPopulation').value,area:$('ccArea').value,search:$('ccSearch').value.trim(),...extra};}
function periodPrevious(r){const n=Math.round((dayMinute(r.to)-dayMinute(r.from))/1440)+1;return {from:addDays(r.from,-n),to:addDays(r.from,-1)};}
function punctualRange(){const r=filters({population:'club'});return $('ccPunctRange').value==='month'?{...r,from:monthStart(r.to),to:monthEnd(r.to)<s.model.today?monthEnd(r.to):s.model.today}:r;}
function error(message){$('ccError').hidden=false;txt('ccError',message);}
function clearError(){$('ccError').hidden=true;txt('ccError','');}
function switchTab(tab){if(!$(`ccPanel-${tab}`))return;s.tab=tab;document.querySelectorAll('.cc-panel').forEach(e=>e.hidden=e.id!==`ccPanel-${tab}`);document.querySelectorAll('.cc-tabs [data-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab));});if(tab==='compliance')loadCompliance();}
async function rpc(name,args,signal){
 const res=await rpcConSesion(name,args,{signal,read:true});
 if(res.error)throw new Error(`${name}: ${res.error.message||'No se pudo completar la consulta'}`);
 if(res.data===null||res.data===undefined)throw new Error(`${name}: respuesta vac\u00eda del servidor`);
 return res.data;
}
async function loadMarks(from,to,signal,token){let cursor=0,ceiling=null,total=null,all=[];const ids=new Set();
 for(let page=0;page<150;page++){
  if(signal.aborted)throw new DOMException('Consulta cancelada','AbortError');
  const data=await rpc('consultar_centro_control_marcaciones_v2',{p_desde:from,p_hasta:to,p_despues:cursor,p_hasta_id:ceiling,p_limite:1500},signal);
  if(total===null){total=Number(data.total);ceiling=Number(data.hasta_id);if(!Number.isFinite(total)||total<0)throw new Error('No se recibio el control total de marcaciones');}
  const batch=data.registros;if(!Array.isArray(batch))throw new Error('Formato de marcaciones inesperado');
  for(const row of batch){if(ids.has(String(row.biotime_id)))throw new Error('Se repitio un ID al paginar. Se conserva la consulta anterior; actualiza de nuevo.');ids.add(String(row.biotime_id));all.push(row);}
  if(token===s.loadToken)txt('ccStatus',`Leyendo marcaciones: ${num(all.length)} de ${num(total)}...`);
  if(all.length===total)return {rows:all,total,ceiling};
  if(!batch.length||Number(data.cursor)<=cursor||all.length>total)throw new Error('La lectura no coincide con el total de Supabase. No se publicaran metricas parciales.');
  cursor=Number(data.cursor);
 }
 throw new Error('El periodo excede el limite de lectura segura. Reduce el rango.');
}
async function load(silent=false){
 const requested={from:$('ccFrom').value,to:$('ccTo').value};const span=(dayMinute(requested.to)-dayMinute(requested.from))/1440;
 if(!Number.isFinite(span)||span<0||span>61){error('Selecciona un rango valido de hasta 62 dias.');return;}
 const now=bogotaNow(),today=iso(now),prior=periodPrevious(requested);
 let from=[requested.from,monthStart(requested.to),prior.from].sort()[0];if(from<HISTORY_START)from=HISTORY_START;
 let to=[requested.to,monthEnd(requested.to)<today?monthEnd(requested.to):today].sort().at(-1);
 if(to<from){error('Los registros disponibles para este modulo comienzan el 23/08/2026.');return;}
 if((dayMinute(to)-dayMinute(from))/1440>94)from=requested.from<monthStart(requested.to)?requested.from:monthStart(requested.to);
 // Un dia de contexto a cada lado permite evaluar turnos que cruzan medianoche.
 from=addDays(from,-1);to=addDays(to,1);
 const token=++s.loadToken;s.abort?.abort();s.abort=new AbortController();const signal=s.abort.signal;
 const timeout=setTimeout(()=>s.abort?.signal===signal&&s.abort.abort(),45000);
 $('ccRefresh').disabled=true;if(!silent)clearError();txt('ccStatus','Consultando personal, programacion y novedades...');
 try{
  await asegurarSesion();
  const [ctx,marks]=await Promise.all([rpc('consultar_centro_control_contexto_v2',{p_desde:from,p_hasta:to},signal),loadMarks(from,to,signal,token)]);
  if(token!==s.loadToken)return;
  const model=buildModel(ctx,marks.rows,ctx.server_time?bogotaNow(new Date(ctx.server_time)):now);
  if(model.diagnostic.invalid)throw new Error('Hay marcas con fecha invalida; se requiere revisar la fuente antes de calcular indicadores.');
  s.model=model;s.range=requested;s.loaded={from,to,total:marks.total,ceiling:marks.ceiling};s.lastLoaded=Date.now();s.page=0;s.compliance=null;s.complianceKey='';
  populateAreas();render();clearError();realtime();
  txt('ccStatus',`Actualizado ${clock(model.now)} (Colombia) \u00b7 ${num(marks.total)} marcaciones leidas completas`);
  if(s.tab==='compliance')loadCompliance();
 }catch(e){if(token!==s.loadToken)return;console.error('Centro de Control',e);if(esErrorAcceso(e)){limpiarDatosPorSesion();mostrarErrorAcceso($('ccError'),e,()=>load());}else{error(e.name==='AbortError'?'La consulta supero el tiempo de espera. Se conservan los datos anteriores; pulsa Actualizar.':`No se actualizo el Centro de Control. ${e.message}. No se reemplazaron los datos por ceros.`);}txt('ccStatus',s.model?'Mostrando la ultima lectura completada':'Lectura no disponible');}
 finally{clearTimeout(timeout);if(token===s.loadToken)$('ccRefresh').disabled=false;}
}
function populateAreas(){const prior=$('ccArea').value;const areas=new Set();for(const e of s.model.ctx.employees||[])areas.add(s.model.person(e.cedula,s.range.to).areaLabel);for(const ev of s.model.events)areas.add(ev.person.areaLabel);$('ccArea').innerHTML='<option value="">Todas las \u00e1reas</option>'+[...areas].sort((a,b)=>a.localeCompare(b)).map(a=>`<option value="${esc(a)}">${esc(a)}</option>`).join('');if(areas.has(prior))$('ccArea').value=prior;}
function chartBars(data,labelKey,valueKey){if(!data.length)return empty();const w=Math.max(570,data.length*35+55),h=240,pad=37,bottom=205,top=22,max=Math.max(1,...data.map(x=>x[valueKey])),bw=(w-pad-15)/data.length;
 let content='';for(let k=0;k<=4;k++){const y=bottom-(bottom-top)*k/4;content+=`<line class="cc-grid" x1="${pad}" y1="${y}" x2="${w}" y2="${y}"/><text class="cc-axis" x="${pad-7}" y="${y+3}" text-anchor="end">${num(max*k/4)}</text>`;}
 data.forEach((x,i)=>{const height=(bottom-top)*x[valueKey]/max,xx=pad+i*bw+bw*.18;content+=`<g><title>${esc(x.tooltip||`${x[labelKey]}: ${num(x[valueKey],1)} personas`)}</title><rect class="cc-bar${x.today?' today':''}" x="${xx}" y="${bottom-height}" width="${Math.max(3,bw*.64)}" height="${height}" rx="3"/><text class="cc-bar-label" x="${xx+bw*.32}" y="${bottom-height-6}" text-anchor="middle">${num(x[valueKey],1)}</text><text class="cc-axis" x="${xx+bw*.32}" y="226" text-anchor="middle">${esc(x[labelKey])}</text></g>`;});
 return `<div class="cc-svg-scroll"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Grafica de personas por fecha" style="min-width:${Math.min(w,1300)}px">${content}</svg></div>`;
}
function allAreaFlow(evs,f){const rows=areaFlow(evs),seen=new Set(rows.map(x=>x.label));for(const e of s.model.ctx.employees||[]){if(e.estado===false)continue;const p=s.model.person(e.cedula,f.to);if(matchPerson(p,f)&&!seen.has(p.areaLabel)){seen.add(p.areaLabel);rows.push({label:p.areaLabel,people:0,personDays:0,marks:0,peak:null});}}return rows.sort((a,b)=>b.people-a.people||a.label.localeCompare(b.label));}
function areaTable(evs,f){const rows=allAreaFlow(evs,f),max=Math.max(1,...rows.map(x=>x.people));return table(['\u00c1rea laboral','Personas distintas','D\u00edas-persona','Registros','Franja con mayor movimiento'],rows.map(a=>[`<button class="cc-link" data-area="${esc(a.label)}">${esc(a.label)}</button>`,`<strong>${num(a.people)}</strong><div class="cc-progress"><i style="width:${a.people/max*100}%"></i></div>`,num(a.personDays),num(a.marks),a.peak?`${String(a.peak.hour).padStart(2,'0')}:00\u2013${String(a.peak.hour+1).padStart(2,'0')}:00<small>${num(a.peak.count)} personas-d\u00eda en esa franja</small>`:'Sin actividad']));}
function renderSummary(){const f=filters(),a=summary(s.model,f),flows=areaFlow(a.events),from=f.from>METRIC_START?f.from:METRIC_START,to=f.to<s.model.today?f.to:s.model.today,daily=dailyFlow(a.events,from,to),best=daily.slice().sort((x,y)=>y.people-x.people)[0];
 txt('ccPeople',num(a.people));txt('ccTopArea',flows[0]?.label||'Sin actividad');txt('ccTopAreaHint',flows[0]?`${num(flows[0].people)} personas distintas en el per\u00edodo`:'No hay registros para el filtro');
 const official=summary(s.model,{...f,population:'club'});txt('ccRate',official.rate===null?'Sin base':`${num(official.rate,1)}%`);txt('ccRateHint',`${num(official.onTime)} de ${num(official.comparable)} jornadas comparables del filtro`);txt('ccMissing',num(a.missing));
 txt('ccRangeLabel',`${pretty(f.from)} \u2014 ${pretty(f.to)}`);
 $('ccDailyChart').innerHTML=chartBars(daily.map(d=>({...d,label:d.date.slice(8,10)+'/'+d.date.slice(5,7),today:d.date===s.model.today,tooltip:`${pretty(d.date)}: ${d.people} personas unicas; ${d.marks} marcaciones`})), 'label','people');
 const todayEvents=selectedEvents(s.model,{...f,from:s.model.today,to:s.model.today}),points=new Map();for(const e of todayEvents)points.set(e.point,(points.get(e.point)||0)+1);const point=[...points].sort((a,b)=>b[1]-a[1])[0];
 $('ccInsights').innerHTML=[best&&best.people?`<strong>Mayor ingreso registrado:</strong> ${pretty(best.date)}, con <strong>${num(best.people)} personas</strong>.<small>Personas con al menos una marcaci\u00f3n, bajo el filtro actual.</small>`:'Sin actividad registrada en este per\u00edodo.',point?`<strong>${esc(point[0])}</strong> registr\u00f3 el mayor movimiento de hoy: <strong>${num(point[1])} marcas</strong>.<small>Registro del punto f\u00edsico; no \u00e1rea laboral.</small>`:'El d\u00eda de hoy no tiene actividad en la lectura y filtros actuales.',`<strong>${num(a.unplanned)} jornadas con marcaci\u00f3n sin programaci\u00f3n.</strong><small>No se califican como impuntualidad. Hace falta el horario confirmado para compararlas.</small>`,`<strong>${num(a.justified)} jornadas con descanso o novedad registrada.</strong><small>Se muestran con causa y vigencia; no se tratan como ausencia injustificada.</small>`].map(t=>`<div class="cc-insight">${t}</div>`).join('');
 $('ccAreaComparison').innerHTML=areaTable(a.events,f);
 const coverage=[];if(f.from<METRIC_START)coverage.push('Los registros anteriores al 27/08 permanecen en el detalle, fuera de los indicadores.');if(f.population!=='club')coverage.push('La puntualidad oficial siempre compara personal del Club. El flujo y detalle respetan el tipo de personal seleccionado.');if(!a.comparable&&a.people)coverage.push('No hay jornadas comparables en este filtro; la presencia se conserva sin inventar horarios.');
 $('ccCoverage').hidden=!coverage.length;txt('ccCoverage',coverage.join(' '));txt('ccIntegrity',`Control de lectura: ${num(s.loaded.total)} registros recibidos de ${num(s.loaded.total)} esperados, hasta ID ${s.loaded.ceiling}. El filtro puede mostrar menos registros. No se eliminaron marcaciones. La clasificaci\u00f3n laboral usa proceso asignado y, si falta, \u00e1rea / centro de costos / cargo; se identifica su fuente en el detalle.`);
}
function renderToday(){const f=filters({from:s.model.today,to:s.model.today});$('ccTodayAreas').innerHTML=inRange(s.model.today,s.loaded)?areaTable(selectedEvents(s.model,f),f):empty('Hoy no esta incluido en los datos cargados. Pulsa Consultar hoy.');txt('ccTodayCaption',`${pretty(s.model.today)} \u00b7 personas \u00fanicas por \u00e1rea laboral; no es ocupaci\u00f3n actual.`);
 const range=filters(),evs=selectedEvents(s.model,range),rows=heatmap(evs,$('ccHeatBy').value),max=Math.max(1,...rows.flatMap(r=>r.hours)),ndays=dates(range.from>METRIC_START?range.from:METRIC_START,range.to<s.model.today?range.to:s.model.today).length;
 txt('ccHeatCaption',ndays===1?'Personas \u00fanicas por franja de 1 hora':`Personas-d\u00eda por franja \u00b7 ${ndays} d\u00edas del filtro`);
 $('ccHeat').innerHTML=rows.length?`<table class="cc-heat"><thead><tr><th>${$('ccHeatBy').value==='area'?'\u00c1rea laboral':'Punto biom\u00e9trico'}</th>${Array.from({length:24},(_,h)=>`<th>${String(h).padStart(2,'0')}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(r.label)}</th>${r.hours.map((n,h)=>`<td class="${n&&n/max>=.75?'peak':n/max>=.4?'medium':''}">${n?`<button data-heat="${esc(r.label)}" data-hour="${h}" title="${esc(r.label)} ${h}:00: ${n} personas-dia; promedio ${num(n/Math.max(1,ndays),1)} por dia" aria-label="${esc(r.label)}, ${h} horas, ${n} personas-dia"><i style="width:${6+18*Math.sqrt(n/max)}px;height:${6+18*Math.sqrt(n/max)}px"></i></button>`:'\u00b7'}</td>`).join('')}</tr>`).join('')}</tbody></table>`:empty('No hay movimiento para dibujar las franjas.');
}
function rankedAreas(rows,bad=false){return rows.length?`<div class="cc-rank-list">${rows.slice(0,5).map(a=>`<div class="cc-rank ${bad?'bad':''}"><div><button class="cc-link" data-area="${esc(a.label)}">${esc(a.label)}</button><small>${bad?a.late:a.onTime} de ${a.comparable} jornadas${a.comparable<5?' \u00b7 base peque\u00f1a':''}</small></div><strong>${num(bad?100-a.rate:a.rate,1)}%</strong></div>`).join('')}</div>`:empty('Todavia no hay jornadas comparables.');}
function renderPunctuality(){const f=punctualRange(),p=punctuality(s.model,f),comp=p.areas.reduce((sum,a)=>sum+a.comparable,0),late=p.areas.reduce((sum,a)=>sum+a.late,0),mins=p.areas.reduce((sum,a)=>sum+a.minutes,0);
 $('ccPunctSummary').innerHTML=[[`${pretty(f.from)} \u2014 ${pretty(f.to)}`,'Per\u00edodo de puntualidad'],[num(comp),'Jornadas comparables'],[num(late),'Jornadas con tardanza'],[num(mins)+' min','Retraso acumulado; no descuento autom\u00e1tico']].map(([v,l])=>`<div class="cc-insight"><strong style="font-size:${l==='Per\u00edodo de puntualidad'?'15':'23'}px">${esc(v)}</strong><small>${esc(l)}</small></div>`).join('');
 const valid=p.areas.filter(a=>a.rate!==null);$('ccBestAreas').innerHTML=rankedAreas(valid.slice().sort((a,b)=>b.rate-a.rate||b.comparable-a.comparable));$('ccLateAreas').innerHTML=rankedAreas(valid.filter(a=>a.late>0).sort((a,b)=>a.rate-b.rate||b.late-a.late),true);
 $('ccPunctAreas').innerHTML=table(['\u00c1rea','Puntualidad','A tiempo','Tarde','Base comparable','Cobertura de horarios','Sin programaci\u00f3n / con marca','Novedades'],p.areas.sort((a,b)=>a.label.localeCompare(b.label)).map(a=>[`<strong>${esc(a.label)}</strong>`,a.rate===null?'Sin base':`${num(a.rate,1)}%${a.comparable<5?'<small>Base menor de 5 jornadas</small>':''}`,num(a.onTime),num(a.late),num(a.comparable),a.scheduled?`${num(a.coverage,1)}%<small>${a.comparable} / ${a.scheduled} con horario evaluable</small>`:'No calculable',num(a.unplanned),num(a.justified)]));
 $('ccLatePeople').innerHTML=table(['Empleado','\u00c1rea','D\u00edas tarde','D\u00edas comparables','Tardanzas / base','Minutos acumulados'],p.employees.filter(e=>e.late>0).map(e=>[`<button class="cc-link" data-person="${esc(e.cedula)}" data-context="punctuality">${esc(e.name)}</button><small>${esc(e.cedula)}</small>`,esc(e.areaLabel),`<strong>${e.late}</strong>`,e.comparable,`${num(e.lateRate,1)}%`,num(e.minutes)]));
}
function causes(j){return (j.notices||[]).map(n=>`${n.label}: ${pretty(n.from)} hasta ${pretty(n.to)} (${n.source})`).join('; ');}
function statusCell(j){const [label,cl]=stateLabels[j.status]||[j.status,''];return pill(label,cl);}
function journeyRows(){const f=filters(),type=$('ccJourneyFilter').value;return s.model.journeys.filter(j=>inRange(j.date,f)&&matchPerson(j.person,f)).filter(j=>type==='all'||(type==='review'?['sin_marca','sin_entrada','conflicto','sin_programacion'].includes(j.status):j.status===type));}
function renderPeople(){const rows=journeyRows(),size=35,maxPage=Math.max(0,Math.ceil(rows.length/size)-1);s.page=Math.min(s.page,maxPage);const part=rows.slice(s.page*size,(s.page+1)*size);
 $('ccJourneyTable').innerHTML=table(['Fecha','Empleado / \u00e1rea','Horario guardado','Entrada de referencia','Estado','Causa / vigencia','Detalle'],part.map(j=>[pretty(j.date),`<strong>${esc(j.person.name)}</strong><small>${esc(j.person.areaLabel)} \u00b7 ${esc(j.code)}</small>`,j.begin?`${esc(j.begin.slice(0,5))}\u2013${esc(clock(j.end?new Date(j.end*60000).toISOString():''))}<small>${esc(j.source)}</small>`:esc(j.source),j.entry?`${esc(j.entry.clock)}<small>${esc(j.entry.alias||j.entry.point)}</small>`:'\u2014',statusCell(j),esc(causes(j)|| (j.status==='sin_programacion'?'Falta horario guardado; no se considera ausencia.':'Sin novedad registrada.')),`<button class="cc-link" data-journey="${esc(j.code)}" data-date="${j.date}">Ver recorrido</button>`]));
 txt('ccPageLabel',rows.length?`${s.page*size+1}\u2013${Math.min((s.page+1)*size,rows.length)} de ${num(rows.length)} jornadas`:'0 jornadas');$('ccPrev').disabled=s.page===0;$('ccNext').disabled=s.page>=maxPage;
}
function renderNotices(){const rows=mergeNotices(s.model,filters());$('ccNotices').innerHTML=table(['Empleado','\u00c1rea','Causa','Desde','Hasta registrado','Fuente / estado'],rows.map(n=>[`<button class="cc-link" data-person="${esc(n.code)}">${esc(n.person.name)}</button>`,esc(n.person.areaLabel),esc(n.label),pretty(n.from),pretty(n.to),`${esc([...new Set(n.sources)].join(' / '))}<small>${esc(n.state)}${n.full?'':' \u00b7 No exime por si sola toda la jornada'}</small>`]));}
function renderTrends(){const f=filters(),evs=selectedEvents(s.model,f),from=f.from>METRIC_START?f.from:METRIC_START,to=f.to<s.model.today?f.to:s.model.today,daily=dailyFlow(evs,from,to),days=['Dom','Lun','Mar','Mi\u00e9','Jue','Vie','S\u00e1b'];
 const week=Array.from({length:7},(_,i)=>{const d=(i+1)%7,rows=daily.filter(x=>new Date(x.date+'T00:00:00Z').getUTCDay()===d);return {label:days[d],people:rows.length?rows.reduce((n,x)=>n+x.people,0)/rows.length:0,tooltip:`${days[d]}: ${rows.length} fechas en el periodo`};});$('ccWeekdayChart').innerHTML=chartBars(week,'label','people');
 const prior=periodPrevious(f);if(prior.from>=METRIC_START&&prior.from>=s.loaded.from&&prior.to<=s.loaded.to){const prevEv=selectedEvents(s.model,{...f,...prior}),prev=dailyFlow(prevEv,prior.from,prior.to),nowAvg=daily.length?daily.reduce((n,x)=>n+x.people,0)/daily.length:0,prevAvg=prev.length?prev.reduce((n,x)=>n+x.people,0)/prev.length:0;$('ccPeriodComparison').innerHTML=`<div class="cc-insight"><strong>${num(nowAvg,1)}</strong> personas por d\u00eda en el per\u00edodo seleccionado.</div><div class="cc-insight"><strong>${num(prevAvg,1)}</strong> personas por d\u00eda en el per\u00edodo anterior.<small>${pretty(prior.from)} \u2014 ${pretty(prior.to)}</small></div><div class="cc-insight">${prevAvg?`${num((nowAvg-prevAvg)/prevAvg*100,1)}% de variaci\u00f3n`:'Sin base para calcular un porcentaje.'}<small>Compara per\u00edodos de igual duraci\u00f3n. Hoy puede estar incompleto.</small></div>`;}else $('ccPeriodComparison').innerHTML=empty('No hay una base anterior completa y confiable para comparar este rango. No se calcula una variacion contra ceros.');
 const emp=new Map();for(const e of evs){const k=e.person.cedula;if(!emp.has(k))emp.set(k,{p:e.person,days:new Set});emp.get(k).days.add(e.date);}const rows=[...emp.values()].sort((a,b)=>b.days.size-a.days.size||a.p.name.localeCompare(b.p.name)).slice(0,20);$('ccAttendanceRanking').innerHTML=table(['Empleado','\u00c1rea','D\u00edas con registro'],rows.map(x=>[`<button class="cc-link" data-person="${esc(x.p.cedula)}">${esc(x.p.name)}</button>`,esc(x.p.areaLabel),num(x.days.size)]));
}
function render(){if(!s.model)return;renderSummary();renderToday();renderPunctuality();renderPeople();renderNotices();renderTrends();}
function showDialog(title,subtitle,html){txt('ccDialogTitle',title);txt('ccDialogSubtitle',subtitle);$('ccDialogBody').innerHTML=html;if(!$('ccDialog').open)$('ccDialog').showModal();}
function openPerson(code,context='period'){const range=context==='punctuality'?punctualRange():filters(),p=s.model.person(code,range.to),js=s.model.journeys.filter(j=>j.code===code&&inRange(j.date,range));
 showDialog(p.name,`${p.areaLabel} \u00b7 ${p.cedula} \u00b7 ${p.areaSource}`,table(['Fecha','Horario','Entrada / punto','Diferencia','Estado','Causa y vigencia','Recorrido'],js.map(j=>[pretty(j.date),j.begin?`${j.begin.slice(0,5)} \u2014 ${clock(j.end?new Date(j.end*60000).toISOString():'')}<small>${esc(j.source)}</small>`:esc(j.source),j.entry?`${j.entry.clock}<small>${esc(j.entry.alias||j.entry.point)}</small>`:'\u2014',j.delta===null||j.delta===undefined?'No comparable':j.delta>0?`${num(j.delta)} min tarde`:j.delta<0?`${num(-j.delta)} min antes`:'Hora exacta',statusCell(j),esc(causes(j)||'Sin novedad registrada'),`<button class="cc-link" data-journey="${esc(code)}" data-date="${j.date}">Abrir</button>`])));
}
function openJourney(code,date){const j=s.model.journeys.find(x=>x.code===code&&x.date===date),p=s.model.person(code,date),ev=s.model.perDay.get(`${code}|${date}`)||[];const next=j?.end&&j.end>=dayMinute(addDays(date,1))?(s.model.perDay.get(`${code}|${addDays(date,1)}`)||[]).filter(e=>e.t<=j.end+120):[];
 showDialog(`Recorrido \u00b7 ${p.name}`,`${pretty(date)} \u00b7 ${p.areaLabel}`,`<p>${j?statusCell(j):''} ${esc(j?causes(j):'')}</p><div class="cc-history"><div class="cc-route">${[...ev,...next].map(e=>`<span class="${e.direction==='out'?'out':''}">${esc(e.clock)} \u00b7 ${esc(e.point)}<em>${esc(e.alias)} \u00b7 ID ${esc(e.id)}${e.date!==date?' \u00b7 '+pretty(e.date):''}</em></span>`).join('')||empty('No hay marcaciones en esa fecha.')}</div></div><p class="cc-footnote">Se presentan los eventos originales. La ultima marca no se declara salida si el dispositivo no la identifica como tal. El recorrido no equivale a horas pagables.</p>`);
}
function openHeat(label,hour){const by=$('ccHeatBy').value,evs=selectedEvents(s.model,filters()).filter(e=>(by==='area'?e.person.areaLabel:e.point)===label&&e.hour===hour),groups=new Map();for(const e of evs){const k=e.person.cedula+'|'+e.date;if(!groups.has(k))groups.set(k,{e,times:[]});groups.get(k).times.push(e.clock);}
 showDialog(`${label} \u00b7 ${String(hour).padStart(2,'0')}:00\u2013${String(hour+1).padStart(2,'0')}:00`,`${groups.size} personas-d\u00eda; no estimacion de ocupacion`,table(['Fecha','Empleado','\u00c1rea laboral','Horas registradas'],[...groups.values()].map(({e,times})=>[pretty(e.date),`<button class="cc-link" data-person="${esc(e.person.cedula)}">${esc(e.person.name)}</button>`,esc(e.person.areaLabel),esc(times.join(' \u00b7 '))])));
}
function openKpi(kind){if(kind==='people'){const seen=new Map();for(const e of selectedEvents(s.model,filters()))seen.set(e.person.cedula,e.person);showDialog('Personas con marcaci\u00f3n','Personas unicas del filtro',table(['Empleado','Documento','\u00c1rea','Clasificaci\u00f3n'],[...seen.values()].sort((a,b)=>a.name.localeCompare(b.name)).map(p=>[`<button class="cc-link" data-person="${esc(p.cedula)}">${esc(p.name)}</button>`,esc(p.cedula),esc(p.areaLabel),p.external?'Externo / extra':p.known?'Personal del Club':'Sin v\u00ednculo'])));}else{$('ccJourneyFilter').value='review';s.page=0;renderPeople();switchTab('people');}}
async function loadCompliance(){if(!s.model)return;const f=filters({population:'club'}),key=f.from+'|'+f.to,token=s.loadToken;if(s.complianceKey===key&&s.compliance){paintCompliance();return;}s.complianceKey=key;$('ccCompliance').innerHTML=empty('Consultando la fuente de cumplimiento semanal...');try{s.compliance=await rpc('consultar_centro_control_cumplimiento_v2',{p_desde:f.from,p_hasta:f.to});if(token!==s.loadToken)return;paintCompliance();}catch(e){if(token===s.loadToken){s.complianceKey='';$('ccCompliance').innerHTML=empty('No fue posible consultar cumplimiento: '+e.message);}}}
function paintCompliance(){const rows=(s.compliance||[]).filter(r=>r.semana_inicio>=METRIC_START&&matchPerson(s.model.person(r.cedula,r.semana_fin),filters({population:'club'})));$('ccCompliance').innerHTML=table(['Empleado','Semana','Programadas','Realizadas (fuente existente)','Estado de la fuente','Auditar'],rows.map(r=>[`<strong>${esc(r.empleado)}</strong><small>${esc(s.model.person(r.cedula,r.semana_fin).areaLabel)}</small>`,`${pretty(r.semana_inicio)} \u2014 ${pretty(r.semana_fin)}`,`${num(r.horas_programadas_netas,2)} h`,r.horas_reales_consolidadas===null?'No calculable':`${num(r.horas_reales_consolidadas,2)} h`,esc(r.estado_cumplimiento||'Por revisar'),`<button class="cc-link" data-audit="${esc(r.cedula)}" data-from="${r.semana_inicio}" data-to="${r.semana_fin}">Abrir auditor\u00eda</button>`]));}
async function openAudit(code,from,to){const token=++s.auditToken;showDialog('Auditor\u00eda semanal',`${s.model.person(code,to).name} \u00b7 ${pretty(from)} \u2014 ${pretty(to)}`,empty('Consultando detalle...'));try{const rows=await rpc('consultar_centro_control_auditoria_v2',{p_cedula:code,p_desde:from,p_hasta:to});if(token!==s.auditToken||!$('ccDialog').open)return;$('ccDialogBody').innerHTML=table(['Fecha','Turno','Programadas','Reales seg\u00fan fuente','Entrada','\u00daltima marca','Estado','Horas aprobadas'],rows.map(r=>[pretty(r.fecha),esc(r.turno||'\u2014'),num(r.horas_programadas_netas,2),num(r.horas_reales_pareadas,2),clock(r.primera_marcacion),clock(r.ultima_marcacion),esc(r.estado_comparacion),num(r.horas_conceptos_aprobadas,2)]));}catch(e){if(token===s.auditToken)$('ccDialogBody').innerHTML=empty(e.message);}}
function exportPunct(){if(!s.model)return;const p=punctuality(s.model,punctualRange());const rows=[['Fecha','Cedula','Empleado','Area','Fuente programacion','Inicio programado','Primera entrada','Punto entrada','Minutos diferencia','Estado','Causa / vigencia'],...p.journeys.map(j=>[j.date,j.code,j.person.name,j.person.areaLabel,j.source,j.begin||'',j.entry?.clock||'',j.entry?.alias||'',j.delta??'',stateLabels[j.status]?.[0]||j.status,causes(j)])];const safe=v=>{let t=String(v??'');if(/^[=+@\-\t\r]/.test(t))t="'"+t;return '"'+t.replace(/"/g,'""')+'"';};const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`Puntualidad_${punctualRange().from}_${punctualRange().to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function preset(which){const today=iso(bogotaNow());$('ccTo').value=today;$('ccFrom').value=which==='today'?today:which==='month'?monthStart(today):addDays(today,-((new Date(today+'T00:00:00Z').getUTCDay()+6)%7));document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('selected',b.dataset.preset===which));load();}
function realtime(){if(s.channel)return;s.channel=supabase.channel('cc-lectura-v2').on('postgres_changes',{event:'UPDATE',schema:'public',table:'app_actualizacion_eventos',filter:'id=eq.centro_control'},()=>scheduleRefresh()).subscribe(status=>txt('ccLive',status==='SUBSCRIBED'?'Actualizaci\u00f3n autom\u00e1tica conectada':'Respaldo autom\u00e1tico cada minuto'));s.timer=setInterval(()=>{if(document.visibilityState==='visible'&&Date.now()-s.lastLoaded>55000)scheduleRefresh();},60000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-s.lastLoaded>60000)scheduleRefresh();});window.addEventListener('beforeunload',()=>{s.abort?.abort();clearInterval(s.timer);clearTimeout(s.debounce);if(s.channel)supabase.removeChannel(s.channel);});}
function scheduleRefresh(){clearTimeout(s.debounce);s.debounce=setTimeout(()=>{if(document.visibilityState==='visible'&&!$('ccRefresh').disabled)load(true);},1800);}
function events(){
 $('ccFilterForm').addEventListener('submit',e=>{e.preventDefault();load();});$('ccRefresh').addEventListener('click',()=>load());
 for(const id of ['ccArea','ccPopulation','ccHeatBy','ccPunctRange','ccJourneyFilter'])$(id).addEventListener('change',()=>{s.page=0;render();if(s.tab==='compliance'&&s.compliance)paintCompliance();});let searchTimer;$('ccSearch').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{s.page=0;render();},160);});
 $('ccPrev').addEventListener('click',()=>{s.page=Math.max(0,s.page-1);renderPeople();});$('ccNext').addEventListener('click',()=>{s.page++;renderPeople();});$('ccExportPunct').addEventListener('click',exportPunct);$('ccReloadCompliance').addEventListener('click',()=>{s.complianceKey='';s.compliance=null;loadCompliance();});$('ccDialogClose').addEventListener('click',()=>{$('ccDialog').close();s.auditToken++;});$('ccDialog').addEventListener('cancel',()=>s.auditToken++);
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.preset){preset(b.dataset.preset);return;}if(b.dataset.tab){switchTab(b.dataset.tab);return;}if(!s.model)return;if(b.dataset.open)openKpi(b.dataset.open);if(b.dataset.area){$('ccArea').value=b.dataset.area;s.page=0;render();}if(b.dataset.person)openPerson(b.dataset.person,b.dataset.context);if(b.dataset.journey)openJourney(b.dataset.journey,b.dataset.date);if(b.dataset.heat)openHeat(b.dataset.heat,+b.dataset.hour);if(b.dataset.audit)openAudit(b.dataset.audit,b.dataset.from,b.dataset.to);});
}
function limpiarDatosPorSesion(){
 s.model=null;s.compliance=null;s.complianceKey='';s.loaded=null;s.auditToken++;clearInterval(s.timer);clearTimeout(s.debounce);
 for(const id of ['ccPeople','ccTopArea','ccRate','ccMissing'])txt(id,'\u2014');
 for(const id of ['ccDailyChart','ccInsights','ccAreaComparison','ccTodayAreas','ccHeat','ccPunctSummary','ccBestAreas','ccLateAreas','ccPunctAreas','ccLatePeople','ccJourneyTable','ccNotices','ccCompliance','ccWeekdayChart','ccPeriodComparison','ccAttendanceRanking','ccDialogBody','ccIntegrity','ccPageLabel'])if($(id))$(id).replaceChildren();
 if($('ccDialog')?.open)$('ccDialog').close();
 if(s.channel){supabase.removeChannel(s.channel);s.channel=null;}
 txt('ccLive','Sesion pendiente de verificar');
}
async function init(){
 const today=iso(bogotaNow());$('ccFrom').value=monthStart(today);$('ccTo').value=today;events();
 let session;try{session=JSON.parse(localStorage.getItem('ccp_sesion')||'null');}catch{}
 txt('ccUser',session?.nombre_completo||session?.usuario||'Sesion por verificar');
 observarSesion(()=>{
  s.abort?.abort();s.loadToken++;limpiarDatosPorSesion();$('ccRefresh').disabled=false;
  mostrarErrorAcceso($('ccError'),new ErrorSesion('AUTH_REQUIRED','Tu sesion cambio o termino. Vuelve a ingresar para consultar tu informacion.'),()=>load());
  txt('ccStatus','Se requiere iniciar sesion');
 });
 await load();
 if(s.model)realtime();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
